spring:
  application:
    name: rabbit-extensions-demo
  rabbitmq:
    addresses: amqp://admin:123456@47.116.96.217:5672/extension
    listener:
      simple:
        #        acknowledge-mode: none  #消息接收确认
        #        acknowledge-mode: auto  #消息接收确认
        acknowledge-mode: manual  #消息接收确认
        prefetch: 1 # 每次从队列中获取消息的条数
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 5000ms # 初始失败等待时长为5秒
          max-retries: 5
    publisher-confirm-type: correlated
#    publisher-confirm-type: correlated   #消息发送确认